### ISSUE TITLE
windows 버전에서 창 크기 변경이 안됩니다.

### ISSUE THREAD

**Issue by ldevil63** [jykim74/BerEditor#4]
최대화 안 되는 건 의도적인 거 같은데 창 크기 변경은 되던 게 안 되는 것 같아요.

![image](https://github.com/jykim74/BerEditor/assets/4695714/a5988f6a-89bf-4d61-9c08-fc356bc0ba61)

**Comment by ldevil63** [comment]
Mac 도 마찬가지입니다.
그리고 Mac M1 에서 돌아가는 것 확인했습니다. 감사합니다~

**Comment by jykim74** [comment]
그러네요. 창 사이즈 조절은 변경 가능 하도록 다음 버전에 반영할께요.
맥 M1 확인 감사합니다^^

**Comment by jykim74** [comment]
> 최대화 안 되는 건 의도적인 거 같은데 창 크기 변경은 되던 게 안 되는 것 같아요.
> 
> ![image](https://user-images.githubusercontent.com/4695714/237853573-a5988f6a-89bf-4d61-9c08-fc356bc0ba61.png)

전체 창 조절 가능하게 변경 했어요.
간단한 수정이라 버전은 안바꾸고 설치 파일만 바꾸었네요.
기존 설치 파일은 지우시고 다시 받아서 설치 하면 됩니다.

**Comment by ldevil63** [comment]
정상적으로 조절되는 것 확인했습니다.
감사합니다~
